services:
  labeler:
    # entrypoint: ./list-labeler
    ports:
      - "${ADMIN_ADDR:-127.0.0.1:8081}:8081"
    command: [
      "--config=/config.yaml",
      "--log-level=0",
      "--listen-addr=:8080",
      "--admin-addr=:8081",
    ]
